// Generated by https://quicktype.io

import { Users } from "src/users/entities/users.entity";
import { Column, Entity, ManyToOne, PrimaryColumn } from "typeorm";

@Entity()
export class Dogs {

    @PrimaryColumn()
    id: string;

    @Column()
    name: string;

    @Column()
    age: number;

    @Column()
    color: string;


    @Column()
    @ManyToOne(() => Users, (user) => user.id, { onDelete: 'CASCADE' })
    owner: string
}
